<ul class="remove-bottom">
    <li class="<?=$this->isCurrentPage('Home') ? 'selected' : '' ?>"><a href="#">Home</a><span class="selector"></span></li>
	<li class="<?=$this->isCurrentPage('Calendar') ? 'selected' : '' ?>"><a href="Calendar">Calendrier</a><span class="selector"></span></li>
	<li class="<?=$this->isCurrentPage('Photos') ? 'selected' : '' ?>"><a href="#">Photos</a><span class="selector"></span></li>
	<li class="<?=$this->isCurrentPage('Menu') ? 'selected' : '' ?>"><a href="#">Menu</a><span class="selector"></span></li>
	<li class="<?=$this->isCurrentPage('Goldenbook') ? 'selected' : '' ?>"><a href="#">Livre d'or</a><span class="selector"></span></li>
	<li class="<?=$this->isCurrentPage('Note') ? 'selected' : '' ?>"><a href="#">Notes</a><span class="selector"></span></li>
	<li class="<?=$this->isCurrentPage('Account') ? 'selected' : '' ?>"><a href="#">Comptes</a><span class="selector"></span></li>
</ul>